version: '3'
services:
  spring-db:
    build:
      context: .
      dockerfile: docker/dockerfile/postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # Persistent data
      - ./docker/db/00-create-db.sql:/docker-entrypoint-initdb.d/00-create-db.sql
  spring-tomcat:
    build:
      context: .
      dockerfile: docker/dockerfile/tomcat
    volumes:
      #- ./docker/tomcat/webapps:/usr/local/tomcat/webapps:cached # Persistent data. Uncomment this if you don't want to redeploy at every boot
      - ./docker/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./docker/tomcat/catalina.properties:/usr/local/tomcat/conf/catalina.properties
      - ./docker/tomcat/user_data:/usr/local/tomcat/user_data
      - ./fcmjava.properties:/usr/local/fcmjava.properties
      - ./stripe.yml:/usr/local/stripe.yml
    ports:
      - "9090:8080"
      - "9000:8000"
    depends_on:
      - spring-db
